<a href="https://colab.research.google.com/github/ADITI9981/ML/blob/main/Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d = tf.constant([2,0,-3,45])
print(tensor_one_d)

tf.Tensor([ 2  0 -3 45], shape=(4,), dtype=int32)


In [6]:
tensor_two_d = tf.constant([
    [1,2,3],
    [3,5,-3],
    [4,5,6]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  3]
 [ 3  5 -3]
 [ 4  5  6]], shape=(3, 3), dtype=int32)


In [8]:
tensor_three_d = tf.constant([
    [[1,2,3],
     [3,4,5]],
    [[1,2,3],
     [3,4,5]],
    [[1,2,3],
     [3,4,5]]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [3 4 5]]], shape=(3, 2, 3), dtype=int32)


In [9]:
print(tensor_three_d.shape)

(3, 2, 3)


In [10]:
tensor_one_d = tf.constant([1,3,4],dtype=tf.float32)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(tensor_one_d)
print(casted_tensor_one_d)


tf.Tensor([1. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor([1 3 4], shape=(3,), dtype=int16)


In [11]:
import numpy as np

In [12]:
np_array = np.array([1,2,3])
print(np_array)

[1 2 3]


In [13]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [14]:
eye_tensor = tf.eye(num_rows=4,num_columns=3,dtype=tf.int32)
print(eye_tensor)

tf.Tensor(
[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]], shape=(4, 3), dtype=int32)


In [15]:
fill_tensor = tf.fill(
    [1,3,4],5, name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [17]:
ones_tensor = tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)


tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [19]:
ones_like = tf.ones_like(
    [
        [1,2,3],
        [4,3,2]
    ],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_like)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [22]:
ones_like_tensor = tf.ones_like(fill_tensor)
print(ones_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [24]:
zeross_like = tf.zeros_like(
    [
        [1,2,3],
        [4,3,2]
    ],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeross_like)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [25]:
rank = tf.rank(
    [3,2,1]
)
print(rank)

tf.Tensor(1, shape=(), dtype=int32)


In [26]:
size = tf.size(
    [3,2,1]
)
print(size)


tf.Tensor(3, shape=(), dtype=int32)


In [30]:
random_tensor = tf.random.normal(
    [3,2],
    mean = 100.0,
    stddev = 1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 99.110374 101.32332 ]
 [100.56125  103.05376 ]
 [101.303215  99.4433  ]], shape=(3, 2), dtype=float32)


In [34]:
uniform_tensor = tf.random.uniform(
    [5,],
    minval=0,
    maxval=8,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor([6.4987793  5.0575867  0.52583885 3.1303186  5.641038  ], shape=(5,), dtype=float32)
